### PR TITLE
Fix problem of calling getData without binding context

### LINKED ISSUE #16: TypeError: Cannot read property 'response' of undefined
Since I installed the latest beta (15) I randomly get this error

image

### PR DESCRIPTION
**Pull request by SferaDev**
* **Issue:** Closes #16

### CODE REVIEW

File: src/react/useD2ApiData.ts [hunk 1]
```diff
@@ -19,21 +19,19 @@ export const useD2ApiData = <T>(apiQuery?: D2ApiDataHookQuery<T>): D2ApiDataHook
...
-                        setState({ loading: false, error });
-                        console.error(error);
-                    }
-                });
-
-            return cancel;
-        }
+        if (!query) return;
+        query
+            .getData()
```
Comment (tokland) [inline src/react/useD2ApiData.ts]: Yep, that was the problem, when an object method is destructured, you lose the binding.
